sudo: required
language: bash
services:
    - docker
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y build-essential python-dev swig
script:
    - make
notifications:
  email: false
